### ISSUE TITLE
Remove hyperlinks

### ISSUE THREAD

**Issue by helrond** [tanseyem/RepoData#3]
Some addresses are hyperlinked to either an email address or a website for the repository - see "West Jefferson Hills Historical Society" and "Stoneboro Historical Society" (both in PA) for examples.

This causes issues when trying to use JSON or CSV data. I think there are a couple of approaches that could be taken:
1. Remove the hyperlinks in the source data and regenerate JSON and CSV (my preference)
2. Account for these hyperlinks in the JSON and CSV conversion scripts

I'm happy to submit a PR which fixes this if I can get a bit of feedback on which approach is preferred.

**Comment by tanseyem** [comment]
Hillel - how prevalent do you think this is? I was able to see what you're talking about with the West Jefferson Hills Historical Society example but not Stoneboro. And with the former, it looks like the URL is 404. 

I am personally OK with Option 1.

**Comment by helrond** [comment]
@tanseyem I don't think there are a lot of them - it seemed to be confined to a couple of files (which is part of why I suggested Option 1). I'll submit a pull request with that change.
